### ISSUE TITLE
1

### ISSUE THREAD

**Issue by m77so** [m77so/gis-try#1]

**Comment by m77so** [comment]
1. 会員登録・ダウンロード https://fgd.gsi.go.jp/download/menu.php
2. QGISのインストール https://www.qgis.org/ja/site/forusers/download.html
2.1 ※ArchLinuxで`No module named 'owslib' `が出る場合は， https://www.archlinux.org/packages/community/x86_64/qgis/ のoptionalのやつを入れるとおさまる
3. 基盤地図情報を読み込めるプラグインのインストールをします．
3.1 https://github.com/mugwort-rc/qgis-fgdloader をzipでダウンロード
3.2. QGISを開いて，上メニューPlugnからプラグインをインストール．ZIPからインストールで先程のZIPを読み込む．

なんか使いにくそう
![image](https://user-images.githubusercontent.com/5989758/72989410-8e4dbb80-3e31-11ea-9b4b-36a99e389c23.png)

**Comment by m77so** [comment]
1. https://www.openstreetmap.org/export#map=14/35.6636/139.7030
1.1 exportを押して範囲を選択してexport
1.2 もっと大きな範囲は？ bbbike / planet osm

kanto download https://download.geofabrik.de/asia/japan/kanto.html
osm.pbfをダウンロードする

converter gdalを入れる
```
% ogr2ogr -f "SQLite" -dsco SPATIALITE=YES kanto.db kanto-latest.osm.pbf 

```
spatialiteにする

BrowserのSpatiaLiteから追加する

Layer->AddLayer->SpatiaLiteで接続して追加．Linesを選択してAdd

Layersについかされる．線路とか入ってるのでフィルタを設定する．
Linesで右クリックしてQueryBuilderを開く．
```
"highway" != ''
```

首都高とかも普通歩かないので除去していく．
```
"highway" != '' AND "ihghway" NOT LIKE  '%motor%'
```

参考サイト https://github.com/AmericanRedCross/workflows/blob/master/converting_pbf_into_spatialite.md

**Comment by m77so** [comment]
![image](https://user-images.githubusercontent.com/5989758/72996500-3073a080-3e3e-11ea-9ed6-0307c380625c.png)

**Comment by m77so** [comment]
plugins -> QNEAT3,Processing をインストール

osgeoがないとき
```
pip install pygdal=="$(gdal-config --version).*"
```

matplotlibも無ければ入れておく
```
pip install matplotlib
```

QNEAT3で到達圏を生成して遊ぶ
```
Processing->Toolbox
QNEAT3->Iso-Areas->Iso-Area as Contours(from Point)
```
![image](https://user-images.githubusercontent.com/5989758/72998644-8b5ac700-3e41-11ea-940d-363e94dec2dd.png)

**Comment by m77so** [comment]
projectionをUTMにしないとだめ

**Comment by m77so** [comment]
```
[QNEAT3Network][calcIsoPoints] Added 1360000 Nodes to iso pointcloud...
[QNEAT3Algorithm] Calculating Iso-Interpolation-Raster using QGIS TIN-Interpolator...
[QNEAT3Algorithm] Calculating Iso-Contours using numpy and matplotlib...
Traceback (most recent call last):
File "/home/m77/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QNEAT3/algs/IsoAreaAsContoursFromPoint.py", line 250, in processAlgorithm
contour_featurelist = net.calcIsoContours(max_dist, interval, output_path)
File "/home/m77/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QNEAT3/Qneat3Framework.py", line 411, in calcIsoContours
band_in = ds_in.GetRasterBand(1)
AttributeError: 'NoneType' object has no attribute 'GetRasterBand'

Execution failed after 309.56 seconds
```
💩

**Comment by m77so** [comment]
```
Loading resulting layers
The following layers were not correctly generated.<ul><li>/tmp/processing_e23f698b6214410db36788267b1e7263/28fbb00d5f3b4d08a69605f0d18180d3/OUTPUT.tif</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
````


```
2020-01-24T01:23:27     WARNING    Caught a coordinate system exception while trying to transform a point. Unable to calculate line length.
2020-01-24T01:23:27     WARNING    Caught a coordinate system exception while trying to transform a point. Unable to calculate line length.
2020-01-24T01:23:27     WARNING    Caught a coordinate system exception while trying to transform a point. Unable to calculate line length.
2020-01-24T01:23:27     WARNING    Caught a coordinate system exception while trying to transform a point. Unable to calculate line length.
2020-01-24T01:23:27     WARNING    Caught a coordinate system exception while trying to transform a point. Unable to calculate line length.
```
